workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.pharmacyPickupApp"  # Your iOS bundle identifier
    scripts:
      - name: Set up key properties
        script: |
          echo "Setting up project..."
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - bhabtish@gmail.com  # Build notifications will be sent here
